/** 应用层使用的类型约束。 */
export type {
  WebDashboardNextAction,
  WebDashboardHighlightJob,
  WebDashboard,
  WebError,
  WebSuccessEnvelope,
  WebErrorEnvelope,
  WebTaskAccepted,
  WebResumeImportResult,
  WebPagination,
  WebJobQuery,
  WebJobMatchMutation,
  WebJobListItem,
  WebJobPage,
  WebJobDetail,
  WebProfileDetail,
  WebProfileMutation,
  WebResumePolishAccepted,
  WebResumePolishStatus,
  WebSource,
  WebSourceChannel,
  WebSourceChannelMutation,
  WebSourceMutation,
  WebSettings,
  WebSettingsMutation,
  WebSourceSyncTaskDetail,
  WebJobDetailBatch,
  WebTask,
  WebAgentRunSummary,
  WebAgentRunDetail,
  WebDiagnostics,
  WebTaskMutation,
  WebResumeDeletionImpact,
  WebResumeDeletionConfirm,
} from './web.js';
export {
  webDashboardNextActionSchema,
  webDashboardHighlightJobSchema,
  webDashboardSchema,
  webErrorSchema,
  webSuccessEnvelopeSchema,
  webErrorEnvelopeSchema,
  webTaskAcceptedSchema,
  webResumeImportResultSchema,
  webPaginationSchema,
  webPagination,
  webJobQuerySchema,
  webJobMatchMutationSchema,
  webJobBulkMatchMutationSchema,
  webJobListItemSchema,
  webJobPageSchema,
  webJobRevisionSchema,
  webJobMatchSchema,
  webJobDetailSchema,
  webProfileSummarySchema,
  webProfileVersionSchema,
  webProfileDetailSchema,
  webProfileMutationSchema,
  webResumePolishRequestSchema,
  webResumePolishAcceptedSchema,
  webResumePolishStatusSchema,
  webSourceSchema,
  webSourceChannelSchema,
  webSourceChannelMutationSchema,
  webSourceMutationSchema,
  webSettingsSchema,
  webSettingsMutationSchema,
  webSourceSyncTaskDetailSchema,
  webJobDetailBatchSchema,
  webTaskSchema,
  webAgentRunSummarySchema,
  webAgentRunDetailSchema,
  webDiagnosticsSchema,
  webTaskMutationSchema,
  webResumeDeletionImpactSchema,
  webResumeDeletionConfirmSchema,
} from './web.js';
export * from './interview-web.js';
export * from './experience-web.js';
export * from './research-web.js';
